//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QUANLYNHANSUEntities : DbContext
    {
        public DB_QUANLYNHANSUEntities()
            : base("name=DB_QUANLYNHANSUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BAOHIEM> TB_BAOHIEM { get; set; }
        public virtual DbSet<TB_BOPHAN> TB_BOPHAN { get; set; }
        public virtual DbSet<TB_CHAMCONG> TB_CHAMCONG { get; set; }
        public virtual DbSet<TB_CHUCVU> TB_CHUCVU { get; set; }
        public virtual DbSet<TB_CONGTY> TB_CONGTY { get; set; }
        public virtual DbSet<TB_DANTOC> TB_DANTOC { get; set; }
        public virtual DbSet<TB_DIEUCHUYEN> TB_DIEUCHUYEN { get; set; }
        public virtual DbSet<TB_DONVI> TB_DONVI { get; set; }
        public virtual DbSet<TB_HOPDONG> TB_HOPDONG { get; set; }
        public virtual DbSet<TB_KCCT> TB_KCCT { get; set; }
        public virtual DbSet<TB_KHENTHUONG_KYLUAT> TB_KHENTHUONG_KYLUAT { get; set; }
        public virtual DbSet<TB_KYCONG> TB_KYCONG { get; set; }
        public virtual DbSet<TB_LOAICA> TB_LOAICA { get; set; }
        public virtual DbSet<TB_LOAICONG> TB_LOAICONG { get; set; }
        public virtual DbSet<TB_NANGLUONG> TB_NANGLUONG { get; set; }
        public virtual DbSet<TB_NHANVIEN> TB_NHANVIEN { get; set; }
        public virtual DbSet<TB_NHANVIEN_CHITIET> TB_NHANVIEN_CHITIET { get; set; }
        public virtual DbSet<TB_NHANVIENPHUCAP> TB_NHANVIENPHUCAP { get; set; }
        public virtual DbSet<TB_PHONGBAN> TB_PHONGBAN { get; set; }
        public virtual DbSet<TB_PHUCAP> TB_PHUCAP { get; set; }
        public virtual DbSet<TB_SYS_FUNC> TB_SYS_FUNC { get; set; }
        public virtual DbSet<TB_SYS_GROUP> TB_SYS_GROUP { get; set; }
        public virtual DbSet<TB_SYS_REPORT> TB_SYS_REPORT { get; set; }
        public virtual DbSet<TB_SYS_RIGHT> TB_SYS_RIGHT { get; set; }
        public virtual DbSet<TB_SYS_RIGHT_REPORT> TB_SYS_RIGHT_REPORT { get; set; }
        public virtual DbSet<TB_SYS_USER> TB_SYS_USER { get; set; }
        public virtual DbSet<TB_TANGCA> TB_TANGCA { get; set; }
        public virtual DbSet<TB_TEST> TB_TEST { get; set; }
        public virtual DbSet<TB_THOIVIEC> TB_THOIVIEC { get; set; }
        public virtual DbSet<TB_TONGIAO> TB_TONGIAO { get; set; }
        public virtual DbSet<TB_TRINHDO> TB_TRINHDO { get; set; }
        public virtual DbSet<TB_UNGLUONG> TB_UNGLUONG { get; set; }
        public virtual DbSet<USER_IN_GROUP> USER_IN_GROUP { get; set; }
        public virtual DbSet<USER_NOTIN_GROUP> USER_NOTIN_GROUP { get; set; }
    }
}
