//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_NHANVIEN()
        {
            this.TB_BAOHIEM = new HashSet<TB_BAOHIEM>();
            this.TB_CHAMCONG = new HashSet<TB_CHAMCONG>();
            this.TB_DIEUCHUYEN = new HashSet<TB_DIEUCHUYEN>();
            this.TB_HOPDONG = new HashSet<TB_HOPDONG>();
            this.TB_KCCT = new HashSet<TB_KCCT>();
            this.TB_KHENTHUONG_KYLUAT = new HashSet<TB_KHENTHUONG_KYLUAT>();
            this.TB_KYCONG = new HashSet<TB_KYCONG>();
            this.TB_NANGLUONG = new HashSet<TB_NANGLUONG>();
            this.TB_NHANVIEN_CHITIET = new HashSet<TB_NHANVIEN_CHITIET>();
            this.TB_NHANVIENPHUCAP = new HashSet<TB_NHANVIENPHUCAP>();
            this.TB_TANGCA = new HashSet<TB_TANGCA>();
            this.TB_THOIVIEC = new HashSet<TB_THOIVIEC>();
            this.TB_UNGLUONG = new HashSet<TB_UNGLUONG>();
        }
    
        public int IDNV { get; set; }
        public string TENNV { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<int> IDDT { get; set; }
        public Nullable<int> IDTG { get; set; }
        public Nullable<int> IDPB { get; set; }
        public Nullable<int> IDBP { get; set; }
        public Nullable<int> IDTD { get; set; }
        public Nullable<int> IDCV { get; set; }
        public Nullable<int> IDCTY { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BAOHIEM> TB_BAOHIEM { get; set; }
        public virtual TB_BOPHAN TB_BOPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CHAMCONG> TB_CHAMCONG { get; set; }
        public virtual TB_CHUCVU TB_CHUCVU { get; set; }
        public virtual TB_CONGTY TB_CONGTY { get; set; }
        public virtual TB_DANTOC TB_DANTOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DIEUCHUYEN> TB_DIEUCHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_HOPDONG> TB_HOPDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_KCCT> TB_KCCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_KHENTHUONG_KYLUAT> TB_KHENTHUONG_KYLUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_KYCONG> TB_KYCONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NANGLUONG> TB_NANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANVIEN_CHITIET> TB_NHANVIEN_CHITIET { get; set; }
        public virtual TB_PHONGBAN TB_PHONGBAN { get; set; }
        public virtual TB_TONGIAO TB_TONGIAO { get; set; }
        public virtual TB_TRINHDO TB_TRINHDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANVIENPHUCAP> TB_NHANVIENPHUCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TANGCA> TB_TANGCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_THOIVIEC> TB_THOIVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_UNGLUONG> TB_UNGLUONG { get; set; }
    }
}
