//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_RIGHT
    {
        public string FUNC_CODE { get; set; }
        public int IDUSER { get; set; }
        public Nullable<int> USERRIGHT { get; set; }
    }
}
