//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TEST
    {
        public int ID { get; set; }
        public string NHOM { get; set; }
        public string CHUCNANG { get; set; }
        public Nullable<bool> XEM { get; set; }
        public Nullable<bool> THEM { get; set; }
        public Nullable<bool> SUA { get; set; }
        public Nullable<bool> XOA { get; set; }
        public Nullable<bool> TRICHXUAT { get; set; }
    }
}
